---
return-email: lore.abad6@gmail.com
return-address: 
  - Lilienthalweg 27
  - 48167, Münster
address:
  - Daniel Hölbling
  - Schillerstrasse 30
  - 5020, Salzburg, Austria
  
subject: Application for the open position of Research Associate in the field of Remote Sensing and Landslides
opening: Dear Mr. Hölbling,
closing: Best regards,
signature: Lorena Abad

output: komaletter::komaletter
---

I write to you regarding the open position as a Research Associate on the Z_GIS department. I would like to start by introducing myself. My name is Lorena Abad, I am an environemntal engineer from Cuenca, Ecuador, studying a masters in Geospatial Technologies, about to finish my masters thesis. 

I was really happy to see that there was a position in Research open for my study levels. Personally, I would love to pursue a career in science and I believe this position is perfect for me to continue expanding my experience in academia. I worked as a researcher in several projects in my hometown university "Universidad de Cuenca", where I pursued my superior studies as an Environmental Engineer. These various jobs led into several publications featured in journals indexed on the LatinIndex data base.

My research interests by then were strongly inclined towards Remote Sensing and Earth Observation. During my studies, my curriculum included the subjects of Cartography and GIS and Remote Sensing. In the latter, I was a teaching assistant after I approved the course, having among my chores: introducing some remote sensing general concepts during lectures, coach students in the use of specialized software such as ENVI and ArcGIS/QGIS for image processing, helping the students with any doubts regarding theoretical and practical content of the course. Later during my studies I developed my final thesis, where I estimated particulate matter concentrations (PM10) in the urban area of my home city using Landsat optical imagery. 

Since then, I collaborated in research projects were I worked with climate data spatial interpolation for environmental analyses, as input for ecological models, and also to develop a web interface for immediate geostatistical inference of meteorological data. After that I got accepted into the Erasmus Mundus Joint Master of Geospatial Technologies held at the three universities: WWU-Münster, Universidade Nova de Lisboa, Universitat Jaume I. During the masters I developed my skills in satellite imagery processing during my courses in Geospatial Data Mining, Remote Sensing, and Unmanned Aerial Vehicles with projects including: "Data Mining Techniques for Satellite Imagery classification", "Land Cover Change Detection of Mangrove Deforestation in Ecuador", and "Renaturation monitoring of the River Aa in Münster, Germany". With this projects I developed my skills in object-based image analysis and classification algorithms. 

I am currently developing my master thesis entitled "Validating a bike network analysis score based on open data as a connectivity measure of urban cycling infrastructure adapted for European cities", supervised by Prof. Dr. Edzer Pebesma. I am planned to graduate by March 2019. In addition I must include my basic knowledge in Geology, Territorial Planning, and Natural Resource Management acquired during my engineering studies. 

On a personal note, I think I believe my skills as a researcher are accompanied by my team work and organizational skills, along with my reliability and responsability. To finalize I would like to add that working in a prestigious academic institution in my field, such as Z_GIS department in the University of Salzburg will certainly be of great gratification for my personal goals. I sincerely hope to be considered for the post. 


Thank you in advance for your consideration.